In [1]:
print("Hello World")

Hello World


In [2]:
x=1

In [3]:
print(x)

1


In [4]:
type(x)

int

In [5]:
y = 1.5

In [6]:
type(y)

float

In [7]:
name = "shah" # Giving a personal name to the variable
type(name)

str

In [8]:
x = 10 
y = 50
z = (x+y)
print(z)

60


In [9]:
print(3+4)

7


In [10]:
print((3-1)/2)

1.0


In [11]:
b1 = True
type(b1)

bool

In [12]:
not True

False

In [13]:
i = 19
if i < 10:
    print('Less than 19')
elif i < 15:
    print('Less than 15')
else:
    print('19 or more')

19 or more


In [14]:
list = [1,2,3,4]
print(list)

[1, 2, 3, 4]


In [15]:
l = []
l.append('e')
l.append('n')
l.insert(0,'p')

l

['p', 'e', 'n']

In [16]:
# Program to add natural
# numbers upto 
# sum = 1+2+3+...+n

# To take input from the user,
# n = int(input("Enter n: "))

n = 10

# initialize sum and counter
sum = 0
i = 1

while i <= n:
    sum = sum + i
    i = i+1    # update counter

# print the sum
print("The sum is", sum)

The sum is 55


In [17]:
print(range(10))

range(0, 10)


In [18]:
for val in "waris":
    if val == "s":
        break
    print(val)

w
a
r
i


In [19]:
name = input("what is your name ?")
type(name)

what is your name ?shah


str

In [20]:
name = input()
type(name)

shah


str

In [21]:
genr = ['Apple', 'Orange', 'Banana','Grape']

# iterate over the list using index
#for i in range (len('genr')):
    #print("I Love", genr[i])
for val in range (len('genr')):
    print("I Love",genr[val])

I Love Apple
I Love Orange
I Love Banana
I Love Grape


In [22]:
# Let's have one more example
name = input("What is your name? ")
print (" It was nice talking you " + name + "!")
age = input("Enter your age? ")
print("Hey, you are already " + age + " years old, " + name + "!")

What is your name? shah
 It was nice talking you shah!
Enter your age? 23
Hey, you are already 23 years old, shah!


In [23]:
# sample list examples

# Print lists in Python (4 Different Ways)

# 1

# Python program to print list 
# using for loop 
a = [1, 2, 3, 4, 5] 
  
# printing the list using loop 
for x in range(len(a)): 
    print(a[x])

1
2
3
4
5


In [24]:
# 2
# Python program to print list 
# without using loop 
  
a = [1, 2, 3, 4, 5] 
  
# printing the list using * operator separated  
# by space  
print(*a) 
  
# printing the list using * and sep operator 
print("printing lists separated by commas") 
  
print(*a, sep = ", ")  
  
# print in new line 
print("printing lists in new line") 
  
print(*a, sep = "\n") 

1 2 3 4 5
printing lists separated by commas
1, 2, 3, 4, 5
printing lists in new line
1
2
3
4
5


In [25]:
# 3
# Python program to print list 
# by Converting a list to a  
# string for display 
a = ["Geeks", "for", "Geeks"] 
  
# print the list using join function() 
print(' '.join(a)) 
  
# print the list by converting a list of  
# integers to string  
a = [1, 2, 3, 4, 5] 

  
print(str(a)[1:-1])

Geeks for Geeks
1, 2, 3, 4, 5


In [26]:
# 4
# Python program to print list 
# print the list by converting a list of  
# integers to string using map 
  
a = [1, 2, 3, 4, 5] 
print(' '.join(map(str, a)))  
print("in new line")
print('\n'.join(map(str, a))) 

1 2 3 4 5
in new line
1
2
3
4
5


In [27]:
name = input("sale is in decline so any alternative? : ")
print("will figure out a way to tackle this issue : " + name + "!")

sale is in decline so any alternative? : yes
will figure out a way to tackle this issue : yes!


In [28]:
def hello():
    result = input("Hi your name:")
    return result


def Main():
    print("Started")
    output = hello()
    #print(output)
    
    
# now we are required to tell python for Main functions existence

if __name__=="__main__":
    Main()
    

Started
Hi your name:shah


In [29]:
def getInteger(): 
    result = int(input("Enter integer: ")) 
    return result 
  
def Main(): 
    print("Started") 
# calling the getInteger function and  
# storing its returned value in the output variable 
    output = getInteger()      
    # print(output) 
  
# now we are required to tell Python  
# for 'Main' function existence 
if __name__=="__main__": 
    Main() 

Started
Enter integer: 10


In [30]:
# Module examples
# math module

import math

def Main():
    num = float(input("enter a number: "))
    # fabs is used to get the absolute value of a decimal
    num = math.fabs(num)
    print(num)
if __name__=="__main__":
    Main()

enter a number: 10
10.0


In [31]:
A1 = True
A2 = False
type(A1)

bool

In [32]:
x=1.0+2.0j
type(x)

complex

In [33]:
sum = 15
i = 1
n = 10
while i <=n:
    sum=sum+i
    i=i+1
    print('sum is ',sum)
    print('i is',i)

sum is  16
i is 2
sum is  18
i is 3
sum is  21
i is 4
sum is  25
i is 5
sum is  30
i is 6
sum is  36
i is 7
sum is  43
i is 8
sum is  51
i is 9
sum is  60
i is 10
sum is  70
i is 11


In [34]:
'''Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, 
between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated 
sequence on a single line'''

'Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, \nbetween 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated \nsequence on a single line'

In [35]:
a=[]
for i in range(2000, 3200):
    if (i%7==0) and (i%5!=0):
        a.append(str(i))  # -> # a.append *note!*
# print (','.join(a))
print(*a , sep = ',')
# print(*a , sep = "\n")

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


In [36]:
#Write a Python program to find the volume of a sphere with diameter 12 cm.
''' Formula: V=4/3 * π * r 3'''
"A=4π2"

pi = 3.1415926535897931
r = 6.0
V = 4.0/3.0*pi* r**3
A = 4*pi* r**2
       
print("Volume of sphere with diameter 12 cm is: ",V)
       
print("Area of sphere with diameter 12 cm is: ",A)

Volume of sphere with diameter 12 cm is:  904.7786842338603
Area of sphere with diameter 12 cm is:  452.3893421169302


In [37]:
# python program to do arithmetic operations

In [38]:
# Storing the input numbers:
num1 = input('Enter first number: ')
num2 = input('Enter second number: ')
# add two numbers
sum = float(num1) + float(num2)
# subtract two numbers
# #min = float(num1) - float(num2)
# multiply two numbers
# mul = float(num1) * float(num2)
# divide two numbers
# div = float(num1) / float(num2)

# Display the sum
# print('The sum is :' ,sum)

print(' The sum of {0} and {1} is {2}'.format(num1,num2, sum))

Enter first number: 10
Enter second number: 54
 The sum of 10 and 54 is 64.0


In [39]:
# Write a program which accepts a sequence of comma-seperated numbers from console and generate a list.

values = input("Input comma seperated numbers : ").split(',')
tuple = tuple(values)
print ("values : " ,values)
print ("tuple(values) : ",tuple)

Input comma seperated numbers : 1,5,6
values :  ['1', '5', '6']
tuple(values) :  ('1', '5', '6')


In [40]:
n=5;
for i in range(n):
    for j in range(i):
        print ('* ', end="")
    print('')

for i in range(n,0,-1):
    for j in range(i):
        print('* ', end="")
    print('')



* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [41]:
print("Third Number Pattern")
lastNumber = 6
for row in range(1, lastNumber):
    for column in range(row, 0, -1):
        print(column, end=' ')
    print("")

Third Number Pattern
1 
2 1 
3 2 1 
4 3 2 1 
5 4 3 2 1 


In [42]:
print("Third Number Pattern")
lastNumber = 6
for row in range(2, lastNumber):
    for column in range(row,1,-1):
        print(column, end=' ')
    print("")

Third Number Pattern
2 
3 2 
4 3 2 
5 4 3 2 


In [43]:
print("Fourth Number Pattern")
lastNumber = 9
for i in range(0, lastNumber):
    for j in range(i, -1, -1):
        print(format(2**j, "4d"), end=' ')
    print("")

Fourth Number Pattern
   1 
   2    1 
   4    2    1 
   8    4    2    1 
  16    8    4    2    1 
  32   16    8    4    2    1 
  64   32   16    8    4    2    1 
 128   64   32   16    8    4    2    1 
 256  128   64   32   16    8    4    2    1 


In [44]:
print("Fourth Number Pattern")
lastNumber = 9
for i in range(9, -1, -1):
    for j in range(0 , i+1):
        print(format(2**i, "4d"), end=' ')
    print("\r")

Fourth Number Pattern
 512  512  512  512  512  512  512  512  512  512 
 256  256  256  256  256  256  256  256  256 
 128  128  128  128  128  128  128  128 
  64   64   64   64   64   64   64 
  32   32   32   32   32   32 
  16   16   16   16   16 
   8    8    8    8 
   4    4    4 
   2    2 
   1 


In [45]:
print("Fourth Number Pattern")
lastNumber = 9
for i in range(9, 0, -1):
    for j in range(0 , i+1):
        print(format(2**i, "4d"), end=' ')
    print("")

Fourth Number Pattern
 512  512  512  512  512  512  512  512  512  512 
 256  256  256  256  256  256  256  256  256 
 128  128  128  128  128  128  128  128 
  64   64   64   64   64   64   64 
  32   32   32   32   32   32 
  16   16   16   16   16 
   8    8    8    8 
   4    4    4 
   2    2 


In [46]:
# Addition of two matrix in python

# Note
# we can treat matrix as a list of list and this sample represents
# [[],[]]

matrixOne = [[6,9,11],
    [2 ,3,8]]
matrixTwo = [[15,18,11],
    [26,16,19]]
result = [[0,0,0],
         [0,0,0]]
# First iterate rows
for i in range(len(matrixOne)):
   # Second iterate columns
   for j in range(len(matrixOne[0])):
       result[i][j] = matrixOne[i][j] + matrixTwo[i][j]
print("Addition of two Matrix In Python")
for res in result:
   print(res)

Addition of two Matrix In Python
[21, 27, 22]
[28, 19, 27]


In [47]:
print("Hi! this is the python game i am interested in\n\t Can this be the day of joy so that i can get\n something new to learn everyday in python.")

Hi! this is the python game i am interested in
	 Can this be the day of joy so that i can get
 something new to learn everyday in python.


In [48]:
# Trying numpy package 
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a)) # printing the type of the array defined.

[1 2 3]
<class 'numpy.ndarray'>


In [49]:
# syntax: for numpy 

# dot -> numpy.dot(a, b, out=None)

# arange(start,stop,step,dtype)

import numpy as np

print("A\n", np.arange(4).reshape(2, 2), "\n") 
  
print("A\n", np.arange(4, 10), "\n") 
  
print("A\n", np.arange(4, 20, 3), "\n") 

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [50]:
# quick sort in python sample

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [51]:
# reversing a word

str(input("Enter a Reverse word = "))[-1::-1]

Enter a Reverse word = sas


'sas'

In [52]:
# word occurences 

s = "I work in bloomberg founded by bloomberg work work"

tokens = s.split(" ")
d = {}
for token in tokens:
    if token in d:
        d[token] += 1
    else:
        d[token] = 1

print(d)

{'I': 1, 'work': 3, 'in': 1, 'bloomberg': 2, 'founded': 1, 'by': 1}


In [53]:
s1 = "I love eating"
s2 = "veggies"
s3 = "fruits"
s1+" " +s2+" and "+s3


# (b) Create fourth variable to store number of fruits you eat everyday. Say for example you eat 2 fruits everyday, in that case print “I love eating 2 fruits everyday”

num_fruits=2

s1+" "+str(num_fruits)+" "+s3+" everyday"


'I love eating 2 fruits everyday'

In [54]:
def mul(a,b):
    return a*b
n1 = input("enter the first number: ")
n1 = int(n1)
n2 = input("enter the second number: ")
n2 = int(n2)
print('mul is: ',mul(n1,n2))

enter the first number: 10
enter the second number: 20
mul is:  200


In [55]:
# sample of regular python use and numpy use 

import numpy as np

In [56]:
%%capture timeit_results
# Regular Python
%timeit python_list_1 = range(1,1000)
python_list_1 = range(1,1000)
python_list_2 = range(1,1000)

#Numpy
%timeit numpy_list_1 = np.arange(1,1000)
numpy_list_1 = np.arange(1,1000)
numpy_list_2 = np.arange(1,1000)

In [57]:
print(timeit_results)

302 ns +- 10.9 ns per loop (mean +- std. dev. of 7 runs, 1000000 loops each)
1.55 us +- 44.8 ns per loop (mean +- std. dev. of 7 runs, 1000000 loops each)



In [58]:
import numpy as np
import sys
import time
l=range(1000)
l
len(l)
print(sys.getsizeof(5)*len(l))
array=np.arange(1000)
print(array.size*array.itemsize)
print(sys.getsizeof(5))

28000
4000
28


In [59]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
print(a.ndim)
print(a.dtype)

[[1 2]
 [3 4]]
2
int32


In [60]:
import numpy as np
np.zeros([3,4])
np.ones([1,3])

array([[1., 1., 1.]])

In [61]:
import numpy as np
np.linspace(1,5,10) # linearly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [62]:
import numpy as np
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [63]:
import numpy as np
x = np.arange(9).reshape((3,3)) 

# reshape is used for assigning 
# the no. of rows and columns for a matrix

print(x)

# printing the min, max, and sum of the assigned matrix
print(x.min())
print(x.max())
print(x.sum())
np.sqrt(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
8
36


array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [64]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
for row in a:
    print(row)
for cell in a.flat:
    print(cell)

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


In [65]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
np.vstack((a,b)) # print stack vertically
np.hstack((a,b)) # print stack horizontally

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [66]:
import numpy as np
np.split(a,3)


[array([[0, 1]]), array([[2, 3]]), array([[4, 5]])]

In [67]:
a = np.arange(6).reshape(3,2)
print(a)
for x in np.nditer(a):
    print (x),
b = a>4 # -> To check which element is highest in the matrix "a"
b
a[b] # -> To return which element is the highest in the array of a matrix

[[0 1]
 [2 3]
 [4 5]]
0
1
2
3
4
5


array([5])

In [68]:
# Numpy array manipulation
# Changing shape -> contains reshape, flat, flatten, ravel
# Transpose operations -> contains transpose, ndarray.T, rollaxis, swapaxes
# Changing Dimensions -> contains broadcast, broadcast_to, expand_dims, squeeze
# Joining Arrays -> contains concatenate, stack, hstack, vstack
# Splitting Arrays -> contains split, hsplit, vsplit
# Adding/Removing Elements -> resize, append, insert, delete, unique


In [69]:
list=[46,32,11,21]
list

# importing functools for reduce()
import functools

print("The sum of the list elements is : ",end="")
print(functools.reduce(lambda a,b : a+b,list))
print(functools.reduce(lambda a,b : a>b,list))
print(functools.reduce(lambda a,b : a<b,list))
print(functools.reduce(lambda a,b : a*b,list))
print(functools.reduce(lambda a,b : a if a > b else b, list))

The sum of the list elements is : 110
False
True
340032
46


In [70]:
# '''Write a Python Program to implement your own myreduce() function which works exactly like
# Python's built-in function reduce()'''

def myreduce(n):
    a = n[0]
    arr_len = len(n)
    arr_bound_value = arr_len - 1
    
    for i in range(arr_len):
        yield a
        if i < arr_bound_value:
            a = a + n[i+1]
            print(i)

In [71]:
for i in myreduce(list):
    print(i)

46
0
78
1
89
2
110


In [72]:
'''List Comprehension Python'''
'''Question 1'''


name = 'Macbook'

name1 = "\n3\n4\n5" 

#str_list = [row[0] for row in name]
str_list1 = [column for column in name1]
#str_list
str_list1

['\n', '3', '\n', '4', '\n', '5']

In [73]:
def find_longest_word(words_list):  
    word_len = []  
    for n in words_list:  
        word_len.append((len(n), n))  
    word_len.sort()  
    return word_len[-1][1]  
  
print(find_longest_word(["PHP", "Exercises", "Backend"]))

Exercises


In [74]:
class Triangle:
    
    def __init__(self,a,b,c):
        self.a = float(a)
        self.b = float(b)
        self.c = float(c)
        
    def area(self):
        s=(self.a + self.b + self.c)/2
        return((s*(s-self.a)*(s-self.b)*(s-self.c))**0.5)

a=input("Enter the value of a = ")
b=input("Enter the value of b = ")
c=input("Enter the value of c = ")
t=Triangle(a, b, c)
print("area: {}".format(t.area()))

Enter the value of a = 10
Enter the value of b = 5
Enter the value of c = 4
area: (6.639192523364281e-16+10.84262422110072j)


In [75]:
# Write a Python program using function concept that maps list of words into a list of integers
# representing the lengths of the corresponding words.
# Hint: If a list [ ab,cde,erty] is passed on to the python function output should come as [2,3,4]
# Here 2,3 and 4 are the lengths of the words in the list.


def map_to_lengths_for(words):
    lengths = []
    for word in words:
        lengths.append(len(word))
    return lengths

if __name__ == "__main__":
    words = ['ab', 'cde', 'erty']
    print (map_to_lengths_for(words))
    
    

[2, 3, 4]


In [76]:
# import pandas as pd

# import numpy as np

# from sqlalchemy import create_engine

# from urllib.parse import quote_plus

# params = quote_plus(r'Driver={SQL Server};Server=server_name;Database=DB_name;Trusted_Connection=yes;')

# engine = create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)

# sql_string = '''SELECT id,author From researches WHERE id < 20 '''

# final_data_fetch = pd.read_sql_query(sql_string, engine)

# final_data_fetch.to_csv('file_name.csv')

In [77]:
# Write a Python function which takes a character 
#(i.e. a string of length 1)
# and returns True if it is 
# a vowel, False otherwise.


def is_vowel(char):
    if char in ['a','e','i','o','u','A','E','I','O','U']:
        return True
    else:
        return False
    

def get_char():
    while True:
        char = input('Input character = ')
        if len(char) > 1:
            print('Not valid char type')
            continue
        else:
            break
    if is_vowel(char):
        print("{}- is vowel".format(char))
    else:
        print("{}- is not vowel".format(char))
        
get_char()

Input character = b
b- is not vowel


In [78]:
# Write a function to compute 5/0 and 
# use try/except to catch the exceptions.

def apply_division(dividend, divisor):
    quotient = 0
    try:
        quotient = dividend / divisor
    except ZeroDivisionError:
        print ('Zero Division Error::Divisor {} is not applicable'.format(divisor))
    return quotient

apply_division(5,0)


Zero Division Error::Divisor 0 is not applicable


0

In [79]:
''' Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.'''

# Moving average 
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3
cumsum, moving_av = [0], []
for i, x in enumerate(mylist, 1):
    cumsum.append(cumsum[i-1] + x)
    if i>=N:
        moving_ave = (cumsum[i] - cumsum[i-N])/N
        moving_av.append(moving_ave)
print(moving_ave)

116.33333333333333


In [80]:
'''Write a function so that the columns of the output matrix are powers of the input vector.'''

''' The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.'''

''' HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.'''


import numpy as np

x = np.array([1,2,3,4,5])
x

def apply_vander(num_list,N=0,increasing=False):
    if N == 0:
        N = len(num_list)
    vander_list = []
    for i in range(N):
        colm_list = []
        for j in range(len(num_list)):
            colm_list.append(num_list[j]**(N-1-i))
        if increasing == True:
            vander_list.insert(0,colm_list)
        else:
            vander_list.append(colm_list)
    return vander_list

vander_list = apply_vander([1,2,3,4,5],5)
np.column_stack(vander_list)

vander_list = apply_vander([1,2,3,4,5],increasing=True)
np.column_stack(vander_list)


vander_list = apply_vander([1,2,3,4,5])
vander_matrix = np.matrix(vander_list)
vander_matrix.T

matrix([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [256,  64,  16,   4,   1],
        [625, 125,  25,   5,   1]])

In [81]:
# import numpy as np
# import pandas as pd
# %matplotlib inline


''' How-to-count-distance-to-the-previous-zero
For each value, count the difference back to the previous zero (or the start of the Series,
whichever is closer)
create a new column 'Y'
Consider a DataFrame df where there is an integer column 'X' '''

import pandas as pd
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]}) 
print(df)
df.info()
df.describe()
df.count()
df.mean()
df.std()
df.min()
df.max()
df.head()

   X
0  7
1  2
2  0
3  3
4  4
5  2
6  5
7  0
8  3
9  4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
X    10 non-null int64
dtypes: int64(1)
memory usage: 160.0 bytes


X
0  7
1  2
2  0
3  3
4  4

In [82]:
import numpy as np
N = 10
a = np.random.rand(N,N) # checking with the random numbers generation in numpy
b = np.zeros((N,N+1)) # assigning zeroes for the variable b
print(a)
print(b)
b[:,:-1] = a
b
a

[[0.70051847 0.69658371 0.96901971 0.65857816 0.99302469 0.06803217
  0.89048668 0.7271592  0.06283614 0.19955523]
 [0.94967181 0.044395   0.17515622 0.57008633 0.75250309 0.83025221
  0.69802165 0.59971402 0.88708179 0.95583243]
 [0.73155717 0.22376457 0.76747201 0.48900754 0.20593609 0.19374156
  0.96514017 0.94098916 0.19935317 0.40430162]
 [0.47145448 0.29985777 0.77217677 0.82025279 0.81066832 0.53156175
  0.05224638 0.34206526 0.01334665 0.29970759]
 [0.40297406 0.38969043 0.69860199 0.45687743 0.30109827 0.10296556
  0.1878957  0.31798033 0.88628251 0.1167282 ]
 [0.87880229 0.94526542 0.10818684 0.59549753 0.44641311 0.13579794
  0.28545672 0.8100002  0.74602412 0.06082238]
 [0.58662821 0.32502327 0.03553087 0.67702205 0.61605977 0.88406982
  0.13956592 0.33821108 0.41813903 0.0273316 ]
 [0.92819027 0.49954729 0.93050784 0.70415561 0.18724923 0.15180522
  0.40555739 0.61870798 0.15775256 0.84168983]
 [0.37740708 0.78336455 0.05568475 0.48095697 0.54000514 0.07774552
  0.68636711

array([[0.70051847, 0.69658371, 0.96901971, 0.65857816, 0.99302469,
        0.06803217, 0.89048668, 0.7271592 , 0.06283614, 0.19955523],
       [0.94967181, 0.044395  , 0.17515622, 0.57008633, 0.75250309,
        0.83025221, 0.69802165, 0.59971402, 0.88708179, 0.95583243],
       [0.73155717, 0.22376457, 0.76747201, 0.48900754, 0.20593609,
        0.19374156, 0.96514017, 0.94098916, 0.19935317, 0.40430162],
       [0.47145448, 0.29985777, 0.77217677, 0.82025279, 0.81066832,
        0.53156175, 0.05224638, 0.34206526, 0.01334665, 0.29970759],
       [0.40297406, 0.38969043, 0.69860199, 0.45687743, 0.30109827,
        0.10296556, 0.1878957 , 0.31798033, 0.88628251, 0.1167282 ],
       [0.87880229, 0.94526542, 0.10818684, 0.59549753, 0.44641311,
        0.13579794, 0.28545672, 0.8100002 , 0.74602412, 0.06082238],
       [0.58662821, 0.32502327, 0.03553087, 0.67702205, 0.61605977,
        0.88406982, 0.13956592, 0.33821108, 0.41813903, 0.0273316 ],
       [0.92819027, 0.49954729, 0.9305078

In [83]:
''' Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of
random numbers.'''

import pandas as pd
range = pd.date_range('1/1/2015', periods=2, freq='H')
range

DatetimeIndex(['2015-01-01 00:00:00', '2015-01-01 01:00:00'], dtype='datetime64[ns]', freq='H')

In [84]:
pd.to_datetime(pd.Series(['Jul 31, 2015', '2010-01-10', None]))

0   2015-07-31
1   2010-01-10
2          NaT
dtype: datetime64[ns]

In [85]:
import numpy as np
df = pd.Series(np.random.randn(100), index=pd.date_range('2012-01-01', periods=100))
df

2012-01-01    0.311750
2012-01-02    0.381373
2012-01-03    1.246539
2012-01-04   -1.341790
2012-01-05   -2.292324
2012-01-06    2.060116
2012-01-07   -1.411846
2012-01-08   -0.224318
2012-01-09    1.298199
2012-01-10   -2.463053
2012-01-11    0.676272
2012-01-12    1.060363
2012-01-13   -1.972557
2012-01-14    0.707346
2012-01-15   -0.478343
2012-01-16    0.142718
2012-01-17    0.073524
2012-01-18    0.576993
2012-01-19    1.053208
2012-01-20    1.525666
2012-01-21   -0.917165
2012-01-22    1.112904
2012-01-23    1.724001
2012-01-24   -0.863977
2012-01-25   -0.758059
2012-01-26   -1.317525
2012-01-27   -0.147724
2012-01-28   -1.142352
2012-01-29    0.888442
2012-01-30    0.617335
                ...   
2012-03-11    0.760082
2012-03-12    2.038907
2012-03-13    0.607771
2012-03-14    0.441022
2012-03-15    0.319975
2012-03-16    0.487946
2012-03-17    1.663648
2012-03-18   -0.340848
2012-03-19    2.175598
2012-03-20    0.285118
2012-03-21    0.071367
2012-03-22   -1.445032
2012-03-23 