In [ ]:
print("Hello World")

In [ ]:
x=1

In [ ]:
print(x)

In [ ]:
type(x)

In [ ]:
y = 1.5

In [ ]:
type(y)

In [ ]:
name=shah
type(name)

In [ ]:
name = "shah" # Giving a personal name to the variable
type(name)

In [ ]:
x = 10 
y = 50
z = (x+y)
print(z)

In [ ]:
print(3+4)

In [ ]:
print 3-7/2

In [ ]:
print((3-1)/2)

In [ ]:
b1 = True
type(b1)

In [ ]:
not True

In [ ]:
i = 19
if i < 10:
    print('Less than 19')
elif i < 15:
    print('Less than 15')
else:
    print('19 or more')

In [ ]:
list = [1,2,3,4]
print(list)

In [ ]:
l = []
l.append('e')
l.append('n')
l.insert(0,'p')

l

In [ ]:
# Program to add natural
# numbers upto 
# sum = 1+2+3+...+n

# To take input from the user,
# n = int(input("Enter n: "))

n = 10

# initialize sum and counter
sum = 0
i = 1

while i <= n:
    sum = sum + i
    i = i+1    # update counter

# print the sum
print("The sum is", sum)

In [ ]:
print(range(10))

In [ ]:
for val in "waris":
    if val == "s":
        break
    print(val)

In [ ]:
name = input("what is your name ?")
type(name)

In [ ]:
name = input()
type(name)

In [ ]:
genr = ['Apple', 'Orange', 'Banana','Grape']

# iterate over the list using index
#for i in range (len('genr')):
    #print("I Love", genr[i])
for val in range (len('genr')):
    print("I Love",genr[val])

In [ ]:
# Let's have one more example
name = input("What is your name? ")
print (" It was nice talking you " + name + "!")
age = input("Enter your age? ")
print("Hey, you are already " + age + " years old, " + name + "!")

In [ ]:
# sample list examples

# Print lists in Python (4 Different Ways)

# 1

# Python program to print list 
# using for loop 
a = [1, 2, 3, 4, 5] 
  
# printing the list using loop 
for x in range(len(a)): 
    print(a[x])

In [ ]:
# 2
# Python program to print list 
# without using loop 
  
a = [1, 2, 3, 4, 5] 
  
# printing the list using * operator separated  
# by space  
print(*a) 
  
# printing the list using * and sep operator 
print("printing lists separated by commas") 
  
print(*a, sep = ", ")  
  
# print in new line 
print("printing lists in new line") 
  
print(*a, sep = "\n") 

In [ ]:
# 3
# Python program to print list 
# by Converting a list to a  
# string for display 
a = ["Geeks", "for", "Geeks"] 
  
# print the list using join function() 
print(' '.join(a)) 
  
# print the list by converting a list of  
# integers to string  
a = [1, 2, 3, 4, 5] 

  
print(str(a)[1:-1])

In [ ]:
# 4
# Python program to print list 
# print the list by converting a list of  
# integers to string using map 
  
a = [1, 2, 3, 4, 5] 
print(' '.join(map(str, a)))  
print("in new line")
print('\n'.join(map(str, a))) 

In [ ]:
name = input("sale is in decline so any alternative? : ")
print("will figure out a way to tackle this issue : " + name + "!")

In [2]:
def hello():
    result = input("Hi your name:")
    return result


def Main():
    print("Started")
    output = hello()
    #print(output)
    
    
# now we are required to tell python for Main functions existence

if __name__=="__main__":
    Main()
    

Started
Hi your name:waris


In [1]:
def getInteger(): 
    result = int(input("Enter integer: ")) 
    return result 
  
def Main(): 
    print("Started") 
# calling the getInteger function and  
# storing its returned value in the output variable 
    output = getInteger()      
    # print(output) 
  
# now we are required to tell Python  
# for 'Main' function existence 
if __name__=="__main__": 
    Main() 

Started
Enter integer: 12


In [1]:
# Module examples
# math module

import math

def Main():
    num = float(input("enter a number: "))
    # fabs is used to get the absolute value of a decimal
    num = math.fabs(num)
    print(num)
if __name__=="__main__":
    Main()

enter a number: 5
5.0


In [ ]:
A1 = True
A2 = False
type(A1)

In [4]:
x=1.0+2.0j
type(x)

complex

In [2]:
sum = 15
i = 1
n = 10
while i <=n:
    sum=sum+i
    i=i+1
    print('sum is ',sum)
    print('i is',i)

sum is  16
i is 2
sum is  18
i is 3
sum is  21
i is 4
sum is  25
i is 5
sum is  30
i is 6
sum is  36
i is 7
sum is  43
i is 8
sum is  51
i is 9
sum is  60
i is 10
sum is  70
i is 11


In [3]:
print(list(range(16)))
# print(list(range(20)))
# print(list(range(60)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [ ]:
'''Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, 
between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated 
sequence on a single line'''

In [5]:
a=[]
for i in range(2000, 3200):
    if (i%7==0) and (i%5!=0):
        a.append(str(i))  # -> # a.append *note!*
# print (','.join(a))
print(*a , sep = ',')
# print(*a , sep = "\n")

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


In [ ]:
#Write a Python program to find the volume of a sphere with diameter 12 cm.
''' Formula: V=4/3 * π * r 3'''
"A=4π2"

pi = 3.1415926535897931
r = 6.0
V = 4.0/3.0*pi* r**3
A = 4*pi* r**2
       
print("Volume of sphere with diameter 12 cm is: ",V)
       
print("Area of sphere with diameter 12 cm is: ",A)

In [ ]:
# python program to do arithmetic operations

In [6]:
# Storing the input numbers:
num1 = input('Enter first number: ')
num2 = input('Enter second number: ')
# add two numbers
sum = float(num1) + float(num2)
# subtract two numbers
# #min = float(num1) - float(num2)
# multiply two numbers
# mul = float(num1) * float(num2)
# divide two numbers
# div = float(num1) / float(num2)

# Display the sum
# print('The sum is :' ,sum)

print(' The sum of {0} and {1} is {2}'.format(num1,num2, sum))

Enter first number: 10
Enter second number: 20
 The sum of 10 and 20 is 30.0


In [7]:
# Write a program which accepts a sequence of comma-seperated numbers from console and generate a list.

values = input("Input comma seperated numbers : ").split(',')
tuple = tuple(values)
print ("values : " ,values)
print ("tuple(values) : ",tuple)

Input comma seperated numbers : 1,2,3,4,5,6,7
values :  ['1', '2', '3', '4', '5', '6', '7']
tuple(values) :  ('1', '2', '3', '4', '5', '6', '7')


In [8]:
n=5;
for i in range(n):
    for j in range(i):
        print ('* ', end="")
    print('')

for i in range(n,0,-1):
    for j in range(i):
        print('* ', end="")
    print('')



* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
print("Third Number Pattern")
lastNumber = 6
for row in range(1, lastNumber):
    for column in range(row, 0, -1):
        print(column, end=' ')
    print("")

In [ ]:
print("Third Number Pattern")
lastNumber = 6
for row in range(2, lastNumber):
    for column in range(row,1,-1):
        print(column, end=' ')
    print("")

In [ ]:
print("Fourth Number Pattern")
lastNumber = 9
for i in range(0, lastNumber):
    for j in range(i, -1, -1):
        print(format(2**j, "4d"), end=' ')
    print("")

In [ ]:
print("Fourth Number Pattern")
lastNumber = 9
for i in range(9, -1, -1):
    for j in range(0 , i+1):
        print(format(2**i, "4d"), end=' ')
    print("\r")

In [ ]:
print("Fourth Number Pattern")
lastNumber = 9
for i in range(9, 0, -1):
    for j in range(0 , i+1):
        print(format(2**i, "4d"), end=' ')
    print("")

In [ ]:
# Addition of two matrix in python

# Note
# we can treat matrix as a list of list and this sample represents
# [[],[]]

matrixOne = [[6,9,11],
    [2 ,3,8]]
matrixTwo = [[15,18,11],
    [26,16,19]]
result = [[0,0,0],
         [0,0,0]]
# First iterate rows
for i in range(len(matrixOne)):
   # Second iterate columns
   for j in range(len(matrixOne[0])):
       result[i][j] = matrixOne[i][j] + matrixTwo[i][j]
print("Addition of two Matrix In Python")
for res in result:
   print(res)

In [ ]:
print("Hi! this is the python game i am interested in\n\t Can this be the day of joy so that i can get\n something new to learn everyday in python.")

In [9]:
# Trying numpy package 
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a)) # printing the type of the array defined.

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
# syntax: for numpy 

# dot -> numpy.dot(a, b, out=None)

# arange(start,stop,step,dtype)

import numpy as np

print("A\n", np.arange(4).reshape(2, 2), "\n") 
  
print("A\n", np.arange(4, 10), "\n") 
  
print("A\n", np.arange(4, 20, 3), "\n") 

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [ ]:
# quick sort in python sample

def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))

In [ ]:
# reversing a word

str(input("Enter a Reverse word = "))[-1::-1]

In [ ]:
# word occurences 

s = "I work in bloomberg founded by bloomberg work work"

tokens = s.split(" ")
d = {}
for token in tokens:
    if token in d:
        d[token] += 1
    else:
        d[token] = 1

print(d)

In [ ]:
s1 = "I love eating"
s2 = "veggies"
s3 = "fruits"
s1+" " +s2+" and "+s3


# (b) Create fourth variable to store number of fruits you eat everyday. Say for example you eat 2 fruits everyday, in that case print “I love eating 2 fruits everyday”

num_fruits=2

s1+" "+str(num_fruits)+" "+s3+" everyday"


In [ ]:
def mul(a,b):
    return a*b
n1 = input("enter the first number: ")
n1 = int(n1)
n2 = input("enter the second number: ")
n2 = int(n2)
print('mul is: ',mul(n1,n2))

In [ ]:
# task to embed a video from youtube
%%HTML
<iframe width="720" height="315" src="https://www.youtube.com/embed/IVrGz8w0H8c" frameborder="0" allowfullscreen></iframe>

In [ ]:
# sample of regular python use and numpy use 

import numpy as np

In [ ]:
%%capture timeit_results
# Regular Python
%timeit python_list_1 = range(1,1000)
python_list_1 = range(1,1000)
python_list_2 = range(1,1000)

#Numpy
%timeit numpy_list_1 = np.arange(1,1000)
numpy_list_1 = np.arange(1,1000)
numpy_list_2 = np.arange(1,1000)

In [ ]:
print(timeit_results)

In [ ]:
import numpy as np
import sys
import time
l=range(1000)
l
len(l)
print(sys.getsizeof(5)*len(l))
array=np.arange(1000)
print(array.size*array.itemsize)
print(sys.getsizeof(5))

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
print(a.ndim)
print(a.dtype)

In [ ]:
import numpy as np
np.zeros([3,4])
np.ones([1,3])

In [ ]:
import numpy as np
np.linspace(1,5,10) # linearly spaced

In [ ]:
import numpy as np
np.logspace(2.0, 3.0, num=4)

In [ ]:
import numpy as np
x = np.arange(9).reshape((3,3)) 

# reshape is used for assigning 
# the no. of rows and columns for a matrix

print(x)

# printing the min, max, and sum of the assigned matrix
print(x.min())
print(x.max())
print(x.sum())
np.sqrt(x)

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
for row in a:
    print(row)
for cell in a.flat:
    print(cell)

In [ ]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
np.vstack((a,b)) # print stack vertically
np.hstack((a,b)) # print stack horizontally

In [ ]:
import numpy as np
np.split(a,3)


In [ ]:
a = np.arange(6).reshape(3,2)
print(a)
for x in np.nditer(a):
    print (x),
b = a>4 # -> To check which element is highest in the matrix "a"
b
a[b] # -> To return which element is the highest in the array of a matrix

In [ ]:
# Numpy array manipulation
# Changing shape -> contains reshape, flat, flatten, ravel
# Transpose operations -> contains transpose, ndarray.T, rollaxis, swapaxes
# Changing Dimensions -> contains broadcast, broadcast_to, expand_dims, squeeze
# Joining Arrays -> contains concatenate, stack, hstack, vstack
# Splitting Arrays -> contains split, hsplit, vsplit
# Adding/Removing Elements -> resize, append, insert, delete, unique


In [ ]:
list=[46,32,11,21]
list

# importing functools for reduce()
import functools

print("The sum of the list elements is : ",end="")
print(functools.reduce(lambda a,b : a+b,list))
print(functools.reduce(lambda a,b : a>b,list))
print(functools.reduce(lambda a,b : a<b,list))
print(functools.reduce(lambda a,b : a*b,list))
print(functools.reduce(lambda a,b : a if a > b else b, list))

In [ ]:
# '''Write a Python Program to implement your own myreduce() function which works exactly like
# Python's built-in function reduce()'''

def myreduce(n):
    a = n[0]
    arr_len = len(n)
    arr_bound_value = arr_len - 1
    
    for i in range(arr_len):
        yield a
        if i < arr_bound_value:
            a = a + n[i+1]
            print(i)

In [ ]:
for i in myreduce(list):
    print(i)

In [ ]:
'''List Comprehension Python'''
'''Question 1'''


name = 'Macbook'

name1 = "\n3\n4\n5" 

#str_list = [row[0] for row in name]
str_list1 = [column for column in name1]
#str_list
str_list1

In [ ]:
lst_set = [tuple([j,i]) for i in range(1,4) for j in range(1,4)]
lst_set

In [ ]:
def find_longest_word(words_list):  
    word_len = []  
    for n in words_list:  
        word_len.append((len(n), n))  
    word_len.sort()  
    return word_len[-1][1]  
  
print(find_longest_word(["PHP", "Exercises", "Backend"]))

In [ ]:
class Triangle:
    
    def __init__(self,a,b,c):
        self.a = float(a)
        self.b = float(b)
        self.c = float(c)
        
    def area(self):
        s=(self.a + self.b + self.c)/2
        return((s*(s-self.a)*(s-self.b)*(s-self.c))**0.5)

a=input("Enter the value of a = ")
b=input("Enter the value of b = ")
c=input("Enter the value of c = ")
t=Triangle(a, b, c)
print("area: {}".format(t.area()))

In [ ]:
# Write a Python program using function concept that maps list of words into a list of integers
# representing the lengths of the corresponding words.
# Hint: If a list [ ab,cde,erty] is passed on to the python function output should come as [2,3,4]
# Here 2,3 and 4 are the lengths of the words in the list.


def map_to_lengths_for(words):
    lengths = []
    for word in words:
        lengths.append(len(word))
    return lengths

if __name__ == "__main__":
    words = ['ab', 'cde', 'erty']
    print (map_to_lengths_for(words))
    
    

In [ ]:
# import pandas as pd

# import numpy as np

# from sqlalchemy import create_engine

# from urllib.parse import quote_plus

# params = quote_plus(r'Driver={SQL Server};Server=server_name;Database=DB_name;Trusted_Connection=yes;')

# engine = create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)

# sql_string = '''SELECT id,author From researches WHERE id < 20 '''

# final_data_fetch = pd.read_sql_query(sql_string, engine)

# final_data_fetch.to_csv('file_name.csv')

In [ ]:
# Write a Python function which takes a character 
#(i.e. a string of length 1)
# and returns True if it is 
# a vowel, False otherwise.


def is_vowel(char):
    if char in ['a','e','i','o','u','A','E','I','O','U']:
        return True
    else:
        return False
    

def get_char():
    while True:
        char = input('Input character = ')
        if len(char) > 1:
            print('Not valid char type')
            continue
        else:
            break
    if is_vowel(char):
        print("{}- is vowel".format(char))
    else:
        print("{}- is not vowel".format(char))
        
get_char()

In [ ]:
# Write a function to compute 5/0 and 
# use try/except to catch the exceptions.

def apply_division(dividend, divisor):
    quotient = 0
    try:
        quotient = dividend / divisor
    except ZeroDivisionError:
        print ('Zero Division Error::Divisor {} is not applicable'.format(divisor))
    return quotient

apply_division(5,0)


In [ ]:
''' Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.'''

# Moving average 
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3
cumsum, moving_av = [0], []
for i, x in enumerate(mylist, 1):
    cumsum.append(cumsum[i-1] + x)
    if i>=N:
        moving_ave = (cumsum[i] - cumsum[i-N])/N
        moving_av.append(moving_ave)
print(moving_ave)

In [ ]:
'''Write a function so that the columns of the output matrix are powers of the input vector.'''

''' The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.'''

''' HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.'''


import numpy as np

x = np.array([1,2,3,4,5])
x

def apply_vander(num_list,N=0,increasing=False):
    if N == 0:
        N = len(num_list)
    vander_list = []
    for i in range(N):
        colm_list = []
        for j in range(len(num_list)):
            colm_list.append(num_list[j]**(N-1-i))
        if increasing == True:
            vander_list.insert(0,colm_list)
        else:
            vander_list.append(colm_list)
    return vander_list

vander_list = apply_vander([1,2,3,4,5],5)
np.column_stack(vander_list)

vander_list = apply_vander([1,2,3,4,5],increasing=True)
np.column_stack(vander_list)


vander_list = apply_vander([1,2,3,4,5])
vander_matrix = np.matrix(vander_list)
vander_matrix.T

In [13]:
# import numpy as np
# import pandas as pd
# %matplotlib inline


''' How-to-count-distance-to-the-previous-zero
For each value, count the difference back to the previous zero (or the start of the Series,
whichever is closer)
create a new column 'Y'
Consider a DataFrame df where there is an integer column 'X' '''

import pandas as pd
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]}) 
print(df)
df.info()
df.describe()
df.count()
df.mean()
df.std()
df.min()
df.max()
df.head()

   X
0  7
1  2
2  0
3  3
4  4
5  2
6  5
7  0
8  3
9  4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
X    10 non-null int64
dtypes: int64(1)
memory usage: 160.0 bytes


X
0  7
1  2
2  0
3  3
4  4

In [ ]:
import numpy as np
N = 10
a = np.random.rand(N,N) # checking with the random numbers generation in numpy
b = np.zeros((N,N+1)) # assigning zeroes for the variable b
print(a)
print(b)
b[:,:-1] = a
b
a

In [ ]:
''' Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of
random numbers.'''

import pandas as pd
range = pd.date_range('1/1/2015', periods=2, freq='H')
range

In [ ]:
pd.to_datetime(pd.Series(['Jul 31, 2015', '2010-01-10', None]))

In [ ]:
import numpy as np
df = pd.Series(np.random.randn(100), index=pd.date_range('2012-01-01', periods=100))
df